version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - aws --version
      - python3 --version  
      - pip3 --version
  build:
    commands:
      - echo Build started on `date`
      # - echo installing aws cli 
      # - sudo apt-get install awscli -y
      - echo installing pip3
      - sudo apt install python3-pip -y
      - echo installing cfn-lint
      - pip3 install cfn-lint
      - modifying the $PATH
      - echo 'export PATH="/home/ubuntu/.local/bin:$PATH"' >> ~/.bashrc
      - echo making the $PATH permanent
      - source ~/.bashrc
      - echo validate cfn template 
      - cfn-lint aws-infra.yaml
      - echo package the cfn template
      - aws cloudformation package --template-file aws-infra.yaml --s3-bucket mynewestfirstbucket --output-template-file aws-infra-artifacts.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - aws-infra.yaml
    - aws-infra-artifacts.yaml