version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - aws --version
      - python3 --version  
      - pip3 --version
  build:
    commands:
      - echo check if AWS CLI installed...
      - aws --version
      - echo check if python installed...
      - python3 --version
      - echo check if pip python package manager installed...
      - pip3 --version
      - echo Installing cfn-lint
      - pip3 install cfn-lint  
      - echo add "/usr/local/bin" to $PATH
      - echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc 
      - echo make the change permanent 
      - source ~/.bashrc   
      - echo Checking cfn-lint installed...
      - cfn-lint --version
  post_build:
    commands:  
      - echo Validating the cfn template
      - cfn-lint aws-infra.yaml
      - echo cfn template Build started on `date`
      - aws cloudformation package --template-file aws-infra.yaml --s3-bucket auto-prod-deployment-bucket --output-template-file output-template.yaml
      - echo Build completed on `date`
artifacts:
  files:
    # "**/*" for the whole
    - output-template.yaml #zipped in the build artifact
    - aws-infra.yaml

 















